### ISSUE TITLE
Issue when you have multiple questions

### ISSUE THREAD

**Issue by mike-st** [simondate/adapt-timed-mcq#2]
Hi this is a great component and very useful! Thanks so much for creating it. 

I just had one issue so far with it. If I am previewing a course and I click on the reveal button and then don't answer the question and move on and click on a second reveal button and let the timer count all the way down. I get an infinite amount of time up feedback notifiers, that I can not stop. I then have to shut down the course. I have forked your component and come up with a fix for this by locking the other questions until the on focus question has been answered. 

You can find the fix here...
[https://github.com/mike-st/adapt-timed-mcq](https://github.com/mike-st/adapt-timed-mcq)

**Comment by simondate** [comment]
Hi,

Thanks for the fix @mike-st . I have never really used the component in production myself but I'm glad you are getting use out of it!

Could you possibly create a Pull request so I can merge it back in?

Thanks!
